spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ho?useSSL=false&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  global:
    pageSize: 5